steps:
  - module_header:
      indent: 2
      sort: false
      break_where: inline

  - simple_align: {}

  - imports:
      list_padding: 2

  - language_pragmas: {}

  - trailing_whitespace: {}

columns: 120
