name:                speff
version:             0.1.0.0
github:              "re-xyr/speff"
license:             BSD3
author:              "Xy Ren"
maintainer:          "xy.r@outlook.com"
copyright:           "2022 Xy Ren"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/re-xyr/speff#readme>

dependencies:
- base
- primitive
- atomic-primops

default-extensions:
- BlockArguments
- DerivingStrategies
- GADTs
- LambdaCase
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- UnicodeSyntax
- KindSignatures
- DataKinds
- PolyKinds
- RoleAnnotations
- TypeFamilies
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- UndecidableInstances
- RankNTypes
- ConstraintKinds
- EmptyCase
- TupleSections

ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wno-unticked-promoted-constructors
- -Wpartial-fields
- -Wunused-type-patterns
# - -ddump-hi
# - -ddump-simpl
# - -ddump-to-file
# - -dsuppress-all
# - -dsuppress-uniques

library:
  source-dirs: src

benchmarks:
  speff-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-T
    dependencies:
    - speff
    - eveff
    - polysemy
    - freer-simple
    - fused-effects
    - mtl
    - tasty-bench
